
import React, { useState, useEffect, useCallback } from 'react';
import { Quote, Sparkles, RefreshCw, Loader2, Bot } from 'lucide-react';

export const AIGeneratedQuote: React.FC = () => {
  const [quote, setQuote] = useState<string | null>(null);
  const [author, setAuthor] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(false);

  const generateQuote = useCallback(async (force = false) => {
    // Check cache first if not forced
    if (!force) {
      const cachedQuote = localStorage.getItem('school_ai_quote');
      const cachedAuthor = localStorage.getItem('school_ai_author');
      const cachedTime = localStorage.getItem('school_ai_quote_time');
      
      // If we have a cached quote from today, use it
      if (cachedQuote && cachedAuthor && cachedTime) {
        const lastFetch = new Date(cachedTime);
        const now = new Date();
        const diffInHours = (now.getTime() - lastFetch.getTime()) / (1000 * 60 * 60);
        
        if (diffInHours < 24) {
          setQuote(cachedQuote);
          setAuthor(cachedAuthor);
          return;
        }
      }
    }

    setIsLoading(true);
    setError(false);
    try {
     const token = await auth.currentUser?.getIdToken();

const response = await fetch("/api/ai/summarize", {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
    Authorization: `Bearer ${token}`
  },
  body: JSON.stringify({ prompt })
});

      if (!response.ok) {
        throw new Error(`Server returned ${response.status}`);
      }

      const data = await response.json();
      // The server returns property "text" which is the string generated by Gemini
      // We need to parse that string as JSON if the prompt asked for JSON
      const parsed = JSON.parse(data.text || '{}');
      
      const newQuote = parsed.citation || "L'excellence est le résultat de la rigueur et de la passion pour la technique.";
      const newAuthor = parsed.auteur || "L'Esprit de Fatick";
      
      setQuote(newQuote);
      setAuthor(newAuthor);

      // Cache the result
      localStorage.setItem('school_ai_quote', newQuote);
      localStorage.setItem('school_ai_author', newAuthor);
      localStorage.setItem('school_ai_quote_time', new Date().toISOString());

    } catch (err) {
      // Check if it's a rate limit error (RESOURCE_EXHAUSTED)
      const errorMsg = err instanceof Error ? err.message : String(err);
      const isQuotaError = errorMsg.includes('429') || errorMsg.includes('RESOURCE_EXHAUSTED');
      
      // Only log errors that are NOT quota related to avoid cluttering consoles with expected limits
      if (!isQuotaError) {
        console.error("Erreur génération citation:", err);
      }

      setError(true);
      const fallbackQuote = "Le succès n'est pas final, l'échec n'est pas fatal : c'est le courage de continuer qui compte.";
      const fallbackAuthor = "Winston Churchill (par défaut)";
      
      setQuote(fallbackQuote);
      setAuthor(fallbackAuthor);
      
      // If we hit quota, cache the fallback for 1 hour to prevent retries
      if (isQuotaError) {
        localStorage.setItem('school_ai_quote', fallbackQuote);
        localStorage.setItem('school_ai_author', fallbackAuthor);
        localStorage.setItem('school_ai_quote_time', new Date().toISOString());
      }
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    generateQuote();
  }, [generateQuote]);

  return (
    <div className="glass rounded-[2.5rem] p-8 border border-indigo-500/20 shadow-xl relative overflow-hidden group">
      {/* Glow effect */}
      <div className="absolute -left-10 -top-10 w-32 h-32 bg-indigo-600/10 rounded-full blur-3xl group-hover:bg-indigo-600/20 transition-all duration-700" />
      
      <div className="flex items-start justify-between mb-4 relative z-10">
        <div className="flex items-center gap-3">
          <div className="p-2.5 bg-indigo-600/10 rounded-xl text-indigo-400">
            <Bot size={20} className={isLoading ? "animate-bounce" : ""} />
          </div>
          <div>
            <h4 className="text-[10px] font-black uppercase text-indigo-500 tracking-[0.2em] flex items-center gap-2">
              Inspiration IA <Sparkles size={12} className="animate-pulse" />
            </h4>
          </div>
        </div>
        <button 
          onClick={() => generateQuote(true)} 
          disabled={isLoading}
          className="p-2 text-slate-500 hover:text-indigo-400 hover:bg-white/5 rounded-xl transition-all disabled:opacity-30"
          title="Nouvelle citation"
        >
          <RefreshCw size={16} className={isLoading ? "animate-spin" : ""} />
        </button>
      </div>

      <div className="relative z-10">
        {isLoading ? (
          <div className="py-6 flex flex-col items-center justify-center gap-3">
            <Loader2 size={24} className="animate-spin text-indigo-500/50" />
            <p className="text-[9px] font-black uppercase text-slate-500 animate-pulse">Consultation de l'Oracle...</p>
          </div>
        ) : (
          <div className="space-y-4 animate-in fade-in slide-in-from-bottom-2 duration-500">
            <div className="relative">
              <Quote size={32} className="absolute -left-2 -top-4 opacity-5 text-indigo-400" />
              <p className="text-[15px] font-bold italic text-slate-700 dark:text-slate-200 leading-relaxed px-2">
                "{quote}"
              </p>
            </div>
            <div className="flex items-center justify-end gap-2 pr-2">
              <div className="h-px w-8 bg-indigo-500/30" />
              <p className="text-[10px] font-black uppercase text-indigo-500 tracking-wider">
                — {author}
              </p>
            </div>
          </div>
        )}
      </div>

      {error && !isLoading && (
        <p className="absolute bottom-2 left-1/2 -translate-x-1/2 text-[7px] font-bold text-slate-500 uppercase opacity-50">
          Mode Secours activé
        </p>
      )}
    </div>
  );
};
